code/QLKS/Models/Room.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.ListRooms = new HashSet<ListRoom>();
            this.ReservationsRooms = new HashSet<ReservationsRoom>();
        }
    
        public string RoomNoID { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> Position { get; set; }
        public string RoomTypeID { get; set; }
        public Nullable<int> RoomStatus { get; set; }
        public string RoomPhone { get; set; }
    
        public virtual ICollection<ListRoom> ListRooms { get; set; }
        public virtual RoomType RoomType { get; set; }
        public virtual ICollection<ReservationsRoom> ReservationsRooms { get; set; }
    }
}

code/QLKS/Models/RoomType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomType
    {
        public RoomType()
        {
            this.RevervationRoomTypes = new HashSet<RevervationRoomType>();
            this.Rooms = new HashSet<Room>();
            this.RoomType_Amenity = new HashSet<RoomType_Amenity>();
            this.RoomType_ServiceFix = new HashSet<RoomType_ServiceFix>();
        }
    
        public string RoomTypeID { get; set; }
        public string RoomTypeName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Depcriptions { get; set; }
    
        public virtual ICollection<RevervationRoomType> RevervationRoomTypes { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<RoomType_Amenity> RoomType_Amenity { get; set; }
        public virtual ICollection<RoomType_ServiceFix> RoomType_ServiceFix { get; set; }
    }
}

code/QLKS/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLKS.Models;

namespace QLKS.Controllers
{
    public class RoomController : Controller
    {
        private Entities db = new Entities();

        //
        // GET: /Room/

        public ActionResult Index()
        {
            ViewRoom view = new ViewRoom()
            {
                ListRoomType = db.RoomTypes.ToList(),
                List = db.Rooms.Include(r => r.RoomType).ToList(),
                Create = new Room()
            };
            ViewBag.RoomTypeID = new SelectList(db.RoomTypes, "RoomTypeID", "RoomTypeName");
            var floor = db.CONFIGCOMPs;
            int floorNo = 10;
            if (floor.FirstOrDefault() != null)
            {
                floorNo = Convert.ToInt32(floor.FirstOrDefault().FloorNo);
            }
            if (floorNo != 0)
            {

                IList<SelectListItem> listValue = new List<SelectListItem>();
                for (int i = 1; i < floorNo; i++)
                {
                    SelectListItem select = new SelectListItem()
                    {
                        Value = Convert.ToString(i),
                        Text = "Tầng " + Convert.ToString(i)
                    };
                    listValue.Add(select);
                }
                ViewBag.Floor = listValue.ToList();
            }
            return View(view); 
        }
        [HttpPost]
        public ActionResult Index(Room room)
        {
            room.RoomStatus = 1;
            if (room.RoomNoID == null)
            {
                var data = db.Database.SqlQuery<System.Int64>("exec GetNextRoomSeq");
                room.RoomNoID = GlobalFunction.addDateToID(data.FirstOrDefault().ToString());
            }
            if (ModelState.IsValid)
            {
                db.Rooms.Add(room);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ViewRoom view = new ViewRoom()
                {
                    ListRoomType = db.RoomTypes.ToList(),
                    List = db.Rooms.Include(r => r.RoomType).ToList(),
                    Create = room
                };
                ViewBag.RoomTypeID = new SelectList(db.RoomTypes, "RoomTypeID", "RoomTypeName");
                var floor = db.CONFIGCOMPs;
                int floorNo = 10;
                if (floor.FirstOrDefault() != null)
                {
                    floorNo = Convert.ToInt32(floor.FirstOrDefault().FloorNo);
                }
                if (floorNo != 0)
                {

                    IList<SelectListItem> listValue = new List<SelectListItem>();
                    for (int i = 1; i < floorNo; i++)
                    {
                        SelectListItem select = new SelectListItem()
                        {
                            Value = Convert.ToString(i),
                            Text = "Tầng " + Convert.ToString(i)
                        };
                        listValue.Add(select);
                    }
                    ViewBag.Floor = listValue.ToList();
                }
                return View(view); 
            }
        }

        //
        // GET: /Room/Details/5

        public ActionResult Details(string id = null)
        {
            Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        //
        // GET: /Room/Create

        public ActionResult Create()
        { 
            return PartialView("Create", new QLKS.Models.Room());
           // return View();
        }

        //
        // POST: /Room/Create

        [HttpPost]
        public ActionResult Create(Room room)
        {
            room.RoomStatus = 1;
            if (room.RoomNoID == null)
            {
                var data = db.Database.SqlQuery<System.Int64>("exec GetNextRoomSeq");
                room.RoomNoID = GlobalFunction.addDateToID(data.FirstOrDefault().ToString());  
            }
            if (ModelState.IsValid)
            {
                db.Rooms.Add(room);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index",room);
            //return View("Index", room);
             
        }

        //
        // GET: /Room/Edit/5

        public ActionResult Edit(string id = null)
        {
            Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            ViewBag.RoomTypeID = new SelectList(db.RoomTypes, "RoomTypeID", "RoomTypeName", room.RoomTypeID);
            return View(room);
        }

        //
        // POST: /Room/Edit/5

        [HttpPost]
        public ActionResult Edit(Room room)
        {
            if (ModelState.IsValid)
            {
                db.Entry(room).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RoomTypeID = new SelectList(db.RoomTypes, "RoomTypeID", "RoomTypeName", room.RoomTypeID);
            return View("Index",room);
        }

        //
        // GET: /Room/Delete/5

        public ActionResult Delete(string id = null)
        {
            Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        //
        // POST: /Room/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id)
        {
            Room room = db.Rooms.Find(id);
            room.RoomStatus = 0;
            //db.Rooms.Remove(room);
            db.Entry(room).State = EntityState.Modified;
            db.SaveChanges(); 

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

code/QLKS/Views/Room/Create.cshtml
@model QLKS.Models.Room

  
@using (Html.BeginForm("Index", "Room"))
{
    @Html.ValidationSummary(true)
      
    @Html.HiddenFor(model => model.RoomNoID)
    @Html.ValidationMessageFor(model => model.RoomNoID)  
    <div class="form-group">
        <div class="control-label col-md-3">
            @Html.LabelFor(model => model.Floor)
        </div>
        <div class="col-md-9">
            @Html.DropDownListFor(model => model.Floor, new SelectList(ViewBag.Floor, "Value", "Text"), "-- Chọn tầng--")
            @Html.ValidationMessageFor(model => model.Floor)
        </div>
    </div>
    <div class="form-group">

        <div class="control-label col-md-3">
            @Html.LabelFor(model => model.Position)
        </div>
        <div class="col-md-9">
            @Html.EditorFor(model => model.Position)
            @Html.ValidationMessageFor(model => model.Position)
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-md-3">
            @Html.LabelFor(model => model.RoomTypeID, "Loại Phòng")
        </div>
        <div class="col-md-9">
            @Html.DropDownList("RoomTypeID", "--Chọn loại phòng--")
            @Html.ValidationMessageFor(model => model.RoomTypeID)
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-md-3">
            @Html.LabelFor(model => model.RoomPhone)
        </div>
        <div class="col-md-9">
            @Html.EditorFor(model => model.RoomPhone)
            @Html.ValidationMessageFor(model => model.RoomPhone)
        </div>
    </div>

   <div class="box_button">
        <button type="submit" value="Create" >Thêm</button>
    </div>
} 

code/QLKS/Views/Room/Delete.cshtml
@model QLKS.Models.Room

@{
    Layout = "../Shared/_LayoutPage.cshtml";
    ViewBag.Title = "Xóa Phòng";
}
<div class="container">
    <div class="messagse">
        <h3>Bạn có chắc chắn xóa phòng?</h3>
    </div>
</div>
<div class="col-md-12">
    <div class="portlet light   ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Xóa Phòng</span>
            </div>

        </div>
        <div class="portlet-body">
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.RoomNoID)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.RoomNoID)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.Floor)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.Floor)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.Position)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.Position)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.RoomType.RoomTypeName)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.RoomType.RoomTypeName)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.RoomStatus)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.RoomStatus)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.RoomPhone)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.RoomPhone)
                </div>
            </div>
            @using (Html.BeginForm())
            {
                <div class="box_button">
                    @Html.ActionLink("Trở về", "Index")
                    <button type="submit" class="btn" value="Xóa">Xóa</button>
                </div>
            }
        </div>
    </div>
</div> 

code/QLKS/Views/Room/Details.cshtml
@model QLKS.Models.Room

@{
    Layout = "../Shared/_LayoutPage.cshtml";
    ViewBag.Title = "Thông tin phòng";
}

<div class="col-md-12">
    <div class="portlet light   ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Phòng</span>
            </div>

        </div>
        <div class="portlet-body">
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.RoomNoID)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.RoomNoID)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.Floor)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.Floor)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.Position)
                </div>

                <div class="col-md-9">
                    @Html.DisplayFor(model => model.Position)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.RoomType.RoomTypeName)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.RoomType.RoomTypeName)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.RoomStatus)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.RoomStatus)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.RoomPhone)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.RoomPhone)
                </div>
            </div>
            <div class="box_button">
                @Html.ActionLink("Sửa", "Edit", new { id = Model.RoomNoID }) |
                @Html.ActionLink("Trở về", "Index")
            </div>
        </div>
    </div>
</div>

code/QLKS/Views/Room/Edit.cshtml
@model QLKS.Models.Room

@{
    Layout = "../Shared/_LayoutPage.cshtml";
    ViewBag.Title = "Sửa phòng";
}

<div class="col-md-12">
    <div class="portlet light   ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Sửa Phòng</span>
            </div>

        </div>
        <div class="portlet-body">
            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true)
                
                @Html.HiddenFor(model => model.RoomStatus) 
                @Html.HiddenFor(model => model.RoomNoID)
                
                <div class="form-group">
                    <div class="control-label col-md-3">
                        @Html.LabelFor(model => model.Floor)
                    </div>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Floor)
                        @Html.ValidationMessageFor(model => model.Floor)
                    </div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3">
                        @Html.LabelFor(model => model.Position)
                    </div>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Position)
                        @Html.ValidationMessageFor(model => model.Position)
                    </div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3">
                        @Html.LabelFor(model => model.RoomTypeID, "Loại phòng")
                    </div>
                    <div class="col-md-9">
                        @Html.DropDownList("RoomTypeID", String.Empty)
                        @Html.ValidationMessageFor(model => model.RoomTypeID)
                    </div>
                </div>
                     
                <div class="form-group">
                    <div class="control-label col-md-3">
                        @Html.LabelFor(model => model.RoomPhone)
                    </div>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.RoomPhone)
                        @Html.ValidationMessageFor(model => model.RoomPhone)
                    </div>
                </div>
                <div class="box_button">
                    @Html.ActionLink("Trở về", "Index")
                    <button type="submit" class="btn" value="Sửa">Lưu</button>
                </div> 
            }

        </div>
    </div>
</div>

code/QLKS/Views/Room/Index.cshtml
@model  QLKS.Models.ViewRoom

@{
    Layout = "../Shared/_LayoutPage.cshtml";
    ViewBag.Title = "Phòng";
}


<div class="col-md-7">
    <div class="portlet light   ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Thông tin chi tiết</span>
            </div>

        </div>
        <div class="portlet-body">
            @Html.Partial("Create", Model.Create)
        </div>
    </div>
</div>
<div class="col-md-5">
    <div class="portlet light  ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Danh sách Loại phòng</span>
            </div>
        </div>
        <div class="portlet-body">
            <table class="scroll">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.ListRoomType.FirstOrDefault().RoomTypeName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ListRoomType.FirstOrDefault().Price)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ListRoomType.FirstOrDefault().Depcriptions)
                        </th>
                    </tr>
                </thead>
                <tbody style="height: 200px;">
                    @foreach (var item in Model.ListRoomType)
                    {
                        <tr>
                            <td style="width: 30%; min-width: 150px;">
                                @Html.DisplayFor(modelItem => item.RoomTypeName)
                            </td>
                            <td style="width: 30%">
                                @Html.DisplayFor(modelItem => item.Price)
                            </td>
                            <td style="width: 40%">
                                @Html.DisplayFor(modelItem => item.Depcriptions)
                            </td>

                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </div>
</div>
<div class="col-md-12">
    <div class="portlet light  ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Danh sách phòng</span>
            </div>
        </div>
        <div class="portlet-body">
            <table id="dataTables" class="table table-striped table-hover scroll">
                <thead>
                    <tr>
                        <th style="width: 10%">
                            @Html.DisplayNameFor(model => model.Create.Floor)
                        </th>
                        <th style="width: 20%">
                            @Html.DisplayNameFor(model => model.Create.Position)
                        </th>
                        <th style="width: 20%">
                            @Html.DisplayNameFor(model => model.Create.RoomType.RoomTypeName)
                        </th>
                        <th style="width: 20%">
                            @Html.DisplayNameFor(model => model.Create.RoomStatus)
                        </th>
                        <th style="width: 20%">
                            @Html.DisplayNameFor(model => model.Create.RoomPhone)
                        </th>
                        <th style="width: 20%"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.List)
                    {
                        <tr>

                            <td style="width: 10%">
                                @Html.DisplayFor(modelItem => item.Floor)
                            </td>
                            <td style="width: 20%">
                                @Html.DisplayFor(modelItem => item.Position)
                            </td>
                            <td style="width: 20%">
                                @Html.DisplayFor(modelItem => item.RoomType.RoomTypeName)
                            </td>
                            <td style="width: 20%">
                                @if (item.RoomStatus == 1)
                                {
                                    <span>Trống</span>
                                }
                                else if (item.RoomStatus == 2)
                                {
                                    <span>Có khách</span>
                                }
                                else if (item.RoomStatus == 3)
                                {
                                    <span>Chờ khách</span>
                                }
                                else if (item.RoomStatus == 4)
                                {
                                    <span>Quá hạn</span>
                                }
                                else if (item.RoomStatus == 5)
                                {
                                    <span>Sửa chữa</span>
                                }
@*Html.DisplayFor(modelItem => item.RoomStatus)*@
                            </td>
                            <td style="width: 20%">
                                @Html.DisplayFor(modelItem => item.RoomPhone)
                            </td>
                            <td style="width: 30%; min-width : 200px">
                                @Html.ActionLink("Sửa", "Edit", new { id = item.RoomNoID }) |
                            @Html.ActionLink("Xem", "Details", new { id = item.RoomNoID }) |
                            @Html.ActionLink("Xóa", "Delete", new { id = item.RoomNoID })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</div>