code/QLKS/Models/Revervation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revervation
    {
        public Revervation()
        {
            this.ReservationsRooms = new HashSet<ReservationsRoom>();
        }
    
        public int ReservationID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> PeopleNumber { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public string Requests { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual RevervationRoomType RevervationRoomType { get; set; }
        public virtual ICollection<ReservationsRoom> ReservationsRooms { get; set; }
    }
}

code/QLKS/Controllers/RevervationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLKS.Models;

namespace QLKS.Controllers
{
    public class RevervationController : Controller
    {
        private Entities db = new Entities();

        //
        // GET: /Revervation/

        public ActionResult Index()
        {
            var revervations = db.Revervations.Where(u => u.Status != 2).Include(r => r.Customer).Include(r => r.RevervationRoomType);
            return View(revervations.ToList());
        }

        //
        // GET: /Revervation/Details/5

        public ActionResult Details(int id = 0)
        {
            Revervation revervation = db.Revervations.Find(id);
            if (revervation == null)
            {
                return HttpNotFound();
            }
            return View(revervation);
        }

        //
        // GET: /Revervation/Create

        public ActionResult Create(ChooseDate datechoose)
        { 
            List<string> result = (from r in db.Rooms
                                join resverRoom in db.ReservationsRooms
                                on r.RoomNoID equals resverRoom.RoomID
                                join resver in db.Revervations
                                on resverRoom.ReservercationID equals resver.ReservationID
                                   where resver.Status != 2 && ((resver.DateOut >= datechoose.DateIn) && (resver.DateOut <= datechoose.DateOut) || (resver.DateIn <= datechoose.DateOut && resver.DateIn >= datechoose.DateIn ))
                                select r.RoomNoID).ToList<string>();
                             ;
            var result1 = (from r in db.Rooms where !result.Contains( r.RoomNoID) && r.RoomStatus == 1 select r).Distinct();
            ViewBag.RoomNoID = new SelectList(result1, "RoomNoID", "Position");
            ViewBag.customer_NationalityID = new SelectList(db.Nationalities, "NationalityID", "NationalityName");
            CreateRevervation revervation = new CreateRevervation();
            Revervation rev = new Revervation();
            Customer cus = new Customer();
            cus.CustomerID = 0;
            rev.DateIn = datechoose.DateIn;
            rev.DateOut = datechoose.DateOut;
            rev.BookingDate = DateTime.Now;
            revervation.revervation = rev;
            revervation.customer = cus;
            return View(revervation);
        }

        //
        // POST: /Revervation/Create

        [HttpPost]
        public ActionResult Create(CreateRevervation reve, string[] ReservationsRoom)
        {
            reve.revervation.CustomerID = reve.customer.CustomerID;
            //reve.revervation.Customer = reve.customer; 
            if (ModelState.IsValid)
            {
                if (reve.customer.CustomerID == 0)
                {
                    var CustomerID = db.Database.SqlQuery<System.Int64>("exec GetNextCustomersSeq").FirstOrDefault();
                    reve.customer.CustomerID = int.Parse(CustomerID.ToString());
                    db.Customers.Add(reve.customer);
                }
                var resevationsID = db.Database.SqlQuery<System.Int64>("exec GetNextReservationsSeq").FirstOrDefault();

                reve.revervation.ReservationID = int.Parse(resevationsID.ToString());

                if (ReservationsRoom != null)
                { 
                    for (int i = 0; i < ReservationsRoom.Count(); i++)
                    {
                        ReservationsRoom room = new ReservationsRoom();
                        room.RoomID = ReservationsRoom[i];
                        room.ReservercationID = reve.revervation.ReservationID; 
                        reve.revervation.ReservationsRooms.Add(room);
                        db.ReservationsRooms.Add(room);
                    }
                }
                reve.revervation.Status = 1;
                reve.revervation.CustomerID = reve.customer.CustomerID;
                db.Revervations.Add(reve.revervation);
                
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            List<string> result = (from r in db.Rooms
                                   join resverRoom in db.ReservationsRooms
                                   on r.RoomNoID equals resverRoom.RoomID
                                   join resver in db.Revervations
                                   on resverRoom.ReservercationID equals resver.ReservationID
                                   where resver.Status != 2 && ((resver.DateOut >= reve.revervation.DateIn) && (resver.DateOut <= reve.revervation.DateOut) || (resver.DateIn <= reve.revervation.DateOut && resver.DateIn >= reve.revervation.DateIn))
                                   select r.RoomNoID).ToList<string>();
            ;
            var result1 = (from r in db.Rooms where !result.Contains(r.RoomNoID) select r).Distinct();
            ViewBag.RoomNoID = new SelectList(result1, "RoomNoID", "Position");
            ViewBag.customer_NationalityID = new SelectList(db.Nationalities, "NationalityID", "NationalityName");
            return View(reve);
        }


        public ActionResult ChooseDateReservation(){
            return View();
        }
        [HttpPost]
        public ActionResult ChooseDateReservation(ChooseDate datechoose)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("Create", datechoose);
            }
            return View();
            
        }
        public ActionResult Deactive(int? id)
        {
            if (id != null && id != 0)
            {
                Revervation rev = db.Revervations.Find(id);
                rev.Status = 2;
                db.Revervations.Attach(rev);
                db.Entry(rev).State = EntityState.Modified;
                db.SaveChanges();
            }
            ViewBag.Message = "Hủy đặt phòng thành công";
            var revervations = db.Revervations.Where(u => u.Status != 2).Include(r => r.Customer).Include(r => r.RevervationRoomType);
            return View("Index",revervations.ToList()); 
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

code/QLKS/Views/Revervation/ChooseDateReservation.cshtml
@model QLKS.Models.ChooseDate
@{
    ViewBag.Title = "Chọn ngày nhận phòng";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="col-md-12">
    <div class="portlet light   ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Chọn ngày</span>
            </div>
        </div>
        <div class="portlet-body">
            @using (Html.BeginForm( ))
            {
                <div class="form-group">
                    <div class="control-label col-md-3">
                        @Html.LabelFor(model => model.DateIn)
                    </div>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.DateIn)
                        @Html.ValidationMessageFor(model => model.DateIn)
                    </div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3">
                        @Html.LabelFor(model => model.DateOut)
                    </div>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.DateOut)
                        @Html.ValidationMessageFor(model => model.DateOut)
                    </div>
                </div>
                <div class ="box_button">
                    <button>Tiếp theo</button> 
                </div>
            }
        </div>
    </div>
</div>

code/QLKS/Views/Revervation/Delete.cshtml
@model QLKS.Models.Revervation

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Revervation</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RevervationRoomType.RoomTypeID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RevervationRoomType.RoomTypeID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Customer.IDCard)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Customer.IDCard)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PeopleNumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PeopleNumber)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateIn)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateIn)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateOut)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateOut)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Requests)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Requests)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BookingDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BookingDate)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

code/QLKS/Views/Revervation/Details.cshtml
@model QLKS.Models.Revervation

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>Revervation</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RevervationRoomType.RoomTypeID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RevervationRoomType.RoomTypeID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Customer.IDCard)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Customer.IDCard)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PeopleNumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PeopleNumber)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateIn)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateIn)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateOut)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateOut)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Requests)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Requests)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BookingDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BookingDate)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

code/QLKS/Views/Revervation/Edit.cshtml
@model QLKS.Models.Revervation

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Revervation</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.ReservationID, "RevervationRoomType")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ReservationID", String.Empty)
            @Html.ValidationMessageFor(model => model.ReservationID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CustomerID, "Customer")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CustomerID", String.Empty)
            @Html.ValidationMessageFor(model => model.CustomerID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PeopleNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PeopleNumber)
            @Html.ValidationMessageFor(model => model.PeopleNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateIn)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateIn)
            @Html.ValidationMessageFor(model => model.DateIn)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateOut)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateOut)
            @Html.ValidationMessageFor(model => model.DateOut)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Requests)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Requests)
            @Html.ValidationMessageFor(model => model.Requests)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Status)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Status)
            @Html.ValidationMessageFor(model => model.Status)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BookingDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BookingDate)
            @Html.ValidationMessageFor(model => model.BookingDate)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

code/QLKS/Views/Revervation/Index.cshtml
@model IEnumerable<QLKS.Models.Revervation>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="col-md-12">
    <div class="portlet light   ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Danh sách đặt phòng</span>
            </div>
            <div class="actions box_button">
                @Html.ActionLink("Đặt phòng", "ChooseDateReservation", "Revervation", new { @class = "btn" })
            </div>

        </div>
        <div class="portlet-body">

            <table class="table table-striped table-hover scroll" id="dataTables" border="1">
                <thead>
                    <tr>
                        <th style ="width: 15%">
                            @Html.DisplayNameFor(model => model.ReservationsRooms)
                        </th>
                        
                        <th style ="width: 15%">
                            @Html.DisplayNameFor(model => model.Customer.Name)
                        </th>
                        <th style ="width: 15%">
                            @Html.DisplayNameFor(model => model.Customer.IDCard)
                        </th>
                        <th style ="width: 10%">
                            @Html.DisplayNameFor(model => model.PeopleNumber)
                        </th>
                         <th style ="width: 10%">
                            @Html.DisplayNameFor(model => model.BookingDate)
                        </th>
                        <th style ="width: 10%">
                            @Html.DisplayNameFor(model => model.DateIn)
                        </th>
                        <th style ="width: 10%">
                            @Html.DisplayNameFor(model => model.DateOut)
                        </th> 
                       
                        <th  style ="width: 25%"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style ="width: 15%" >
                                @{var i_count = 0; }
                                @foreach (var modelItem in item.ReservationsRooms)
                                {
                                    i_count++;
                                    @Html.DisplayFor(itemmodel => modelItem.Room.Position) 
                       
                                    if (i_count < item.ReservationsRooms.Count())
                                    {
                                    <span>,</span>
                                    }
                                }
                            </td>
                            
                            <td  style ="width: 15%">
                                @Html.DisplayFor(modelItem => item.Customer.Name)
                            </td>
                            <td  style ="width: 15%">
                                @Html.DisplayFor(modelItem => item.Customer.IDCard)
                            </td>
                            <td  style ="width: 10%">
                                @Html.DisplayFor(modelItem => item.PeopleNumber)
                            </td>
                            <td  style ="width: 10%">
                                @Html.DisplayFor(modelItem => item.BookingDate)
                            </td>
                            <td  style ="width: 10%">
                                @Html.DisplayFor(modelItem => item.DateIn)
                            </td>
                            <td  style ="width: 10%">
                                @Html.DisplayFor(modelItem => item.DateOut)
                            </td> 
                            
                            <td  style ="width: 25%">
                                @Html.ActionLink("Nhận phòng",  "../CheckIn/CreateCheckin", new { resvationsID = item.ReservationID }) |
                                @Html.ActionLink("Hủy đặt phòng", "Deactive", new { id = item.ReservationID }, new { onclick="return confirm('Bạn có chắc chắn muốn hủy đặt phòng?')" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>