code/QLKS/Models/Amenity.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amenity
    {
        public string AmenityID { get; set; }
        public string AmenityName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public string AmenityUnit { get; set; }
    
        public virtual RoomType_Amenity RoomType_Amenity { get; set; }
    }
}

code/QLKS/Controllers/AmenityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLKS.Models;

namespace QLKS.Controllers
{
    public class AmenityController : Controller
    {
        private Entities db = new Entities();

        public string AddAmenity(string ids)
        {
            string result = "";
            if (ids != "")
            {
                string[] listid = ids.Split(',');
                if (listid.Length > 1)
                {
                    for (int i = 0; i < listid.Length - 1; i++)
                    {
                        var amenity = db.Amenities.Find(listid[i]);
                        result += "<tr>"
                           + "<td>"+amenity.AmenityName+"</td>"
                           + "<td>"+amenity.AmenityUnit+"</td>"
                           + "<td><input type='number' class = 'form-control form-control-inline input-medium' name ='number' value='1' /></td>"
                           + "<td>"+ amenity.Price
                           + "<input type = 'hidden' name = 'price' value ='" + amenity.Price + "'/>"
                           +"</td>"
                           + "<td><span class ='total_price'>" + amenity.Price + "</span></td>"
                           + "<td><span class = 'remove' data = "+ amenity.AmenityID +">remove</span></td>"
                           + "</tr>";
                    }
                }
            }
            return result;

        }



        //
        // GET: /Amenity/

        public ActionResult Index()
        {
            return View(db.Amenities.ToList());
        }

        //
        // GET: /Amenity/Details/5

        public ActionResult Details(string id = null)
        {
            Amenity amenity = db.Amenities.Find(id);
            if (amenity == null)
            {
                return HttpNotFound();
            }
            return View(amenity);
        }

        //
        // GET: /Amenity/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Amenity/Create

        [HttpPost]
        public ActionResult Create(Amenity amenity)
        {
            if (ModelState.IsValid)
            {
                var data = db.Database.SqlQuery<System.Int64>("exec GetNextAmenitySeq");
                amenity.AmenityID = GlobalFunction.addDateToID(data.FirstOrDefault().ToString());
                db.Amenities.Add(amenity);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(amenity);
        }

        //
        // GET: /Amenity/Edit/5

        public ActionResult Edit(string id = null)
        {
            Amenity amenity = db.Amenities.Find(id);
            if (amenity == null)
            {
                return HttpNotFound();
            }
            return View(amenity);
        }

        //
        // POST: /Amenity/Edit/5

        [HttpPost]
        public ActionResult Edit(Amenity amenity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(amenity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(amenity);
        }

        //
        // GET: /Amenity/Delete/5

        public ActionResult Delete(string id = null)
        {
            Amenity amenity = db.Amenities.Find(id);
            if (amenity == null)
            {
                return HttpNotFound();
            }
            return View(amenity);
        }

        //
        // POST: /Amenity/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id)
        {
            Amenity amenity = db.Amenities.Find(id);
            db.Amenities.Remove(amenity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

code/QLKS/Views/Amenity/AmenityInvoice.cshtml
@model QLKS.Models.Amenity

 
    <tr>
        <td>
            @Html.DisplayFor(modelItem => Model.AmenityName)
            @Html.HiddenFor(modelItem => Model.AmenityID)
        </td>
        <td>
             <input name ="soLuong" value ="1" type ="number"/> 
        </td>
        <td>
             @Html.DisplayFor(modelItem => Model.Price)
            @Html.HiddenFor(modelItem => Model.Price)
        </td>
         
    </tr> 

code/QLKS/Views/Amenity/Create.cshtml
@model QLKS.Models.Amenity

@{
    Layout = "../Shared/_LayoutPage.cshtml";
    ViewBag.Title = "Create";
}

<div class="col-md-12">
    <div class="portlet light   ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Tạo mới thiết bị</span>
            </div>

        </div>
        <div class="portlet-body">

            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true)
     
                <div class="form-group">
                    <div class="control-label col-md-3">
                        @Html.LabelFor(model => model.AmenityName)
                    </div>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.AmenityName)
                        @Html.ValidationMessageFor(model => model.AmenityName)
                    </div>
                </div>
                <div class="form-group">

                    <div class="control-label col-md-3">
                        @Html.LabelFor(model => model.Price)
                    </div>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Price)
                        @Html.ValidationMessageFor(model => model.Price)
                    </div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3">
                        @Html.LabelFor(model => model.Description)
                    </div>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Description)
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>
                </div>
     

                <div class="box_button">
                    @Html.ActionLink("Trở lại","Index","Amenity",htmlAttributes:new {@class = "btn"})
                    <button type="submit" value="Create">Thêm</button>
                </div>
            }
        </div>
    </div>
</div>

code/QLKS/Views/Amenity/Delete.cshtml
@model QLKS.Models.Amenity

@{
    Layout = "../Shared/_LayoutPage.cshtml";
    ViewBag.Title = "Xóa thiết bị";
}
<div class="container">
    <div class="messagse">
        <h3>Bạn có chắc chắn xóa thiết bị?</h3>
    </div>
</div>
<div class="col-md-12">
    <div class="portlet light   ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Xóa thiết bị</span>
            </div>

        </div>
        <div class="portlet-body">
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.AmenityName)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.AmenityName)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.Price)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.Price)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.Description)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.Description)
                </div>
            </div>
            @using (Html.BeginForm())
            {
                <div class="box_button">

                    @Html.ActionLink("Trở về", "Index")
                    <button class="btn">Xóa</button>
                </div>
            }
        </div>
    </div>
</div>

code/QLKS/Views/Amenity/Details.cshtml
@model QLKS.Models.Amenity

@{
    Layout = "../Shared/_LayoutPage.cshtml";
    ViewBag.Title = "Details";
}

<div class="col-md-12">
    <div class="portlet light   ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Phòng</span>
            </div>

        </div>
        <div class="portlet-body">
            <div class="form-group">

                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.AmenityName)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.AmenityName)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.Price)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.Price)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.Description)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.Description)
                </div>
            </div>
            <div class="box_button">
                @Html.ActionLink("Sửa", "Edit", new { id = Model.AmenityID }) |
                @Html.ActionLink("Trở về", "Index")
            </div>
        </div>
    </div>
</div>

code/QLKS/Views/Amenity/Edit.cshtml
@model QLKS.Models.Amenity

@{
    Layout = "../Shared/_LayoutPage.cshtml";
    ViewBag.Title = "Edit";
}

<div class="col-md-12">
    <div class="portlet light   ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Sửa thiết bị</span>
            </div>

        </div>

        @using (Html.BeginForm())
        {
            @Html.ValidationSummary(true)   

            @Html.HiddenFor(model => model.AmenityID)
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.LabelFor(model => model.AmenityName)
                </div>
                <div class="col-md-9">
                    @Html.EditorFor(model => model.AmenityName)
                    @Html.ValidationMessageFor(model => model.AmenityName)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.LabelFor(model => model.Price)
                </div>
                <div class="col-md-9">
                    @Html.EditorFor(model => model.Price)
                    @Html.ValidationMessageFor(model => model.Price)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.LabelFor(model => model.Description)
                </div>
                <div class="col-md-9">
                    @Html.EditorFor(model => model.Description)
                    @Html.ValidationMessageFor(model => model.Description)
                </div>
            </div>
        
            <div class="box_button">
                @Html.ActionLink("Trở về", "Index")
                <button type="submit" class="btn" value="Sửa">Lưu</button>
            </div>  
        }
    </div>
</div>

code/QLKS/Views/Amenity/Index.cshtml
@model IEnumerable<QLKS.Models.Amenity>


@{
    Layout = "../Shared/_LayoutPage.cshtml";
    ViewBag.Title = "Danh sách trang/thiết bị";
}

<div class="col-md-12">
    <div class="portlet light   ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Thiết bị</span>
            </div>
            <div class ="actions box_button">  
                @Html.ActionLink("Thêm thiết bị", "Create", "Amenity", htmlAttributes: new { @class = "btn" })
            </div> 
        </div>
        <div class="portlet-body">
            
            <table id="dataTables" class="table table-striped table-hover scroll">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.AmenityName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Price)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Description)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tr>
                        <td style ="width: 30%">
                            @Html.DisplayFor(modelItem => item.AmenityName)
                        </td>
                        <td  style ="width: 30%">
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td  style ="width: 30%">
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td style ="width: 10%; min-width : 200px">
                            @Html.ActionLink("Sửa", "Edit", new { id = item.AmenityID }) |
                            @Html.ActionLink("Xem", "Details", new { id = item.AmenityID }) |
                            @Html.ActionLink("Xóa", "Delete", new { id = item.AmenityID })
                        </td>
                    </tr>
                }

            </table>

        </div>
    </div>
</div>