code/QLKS/Controllers/RoomTypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLKS.Models;

namespace QLKS.Controllers
{
    public class RoomTypeController : Controller
    {
        private Entities db = new Entities();

        
        public ActionResult Search(string id)
        {
            var rooms = db.Rooms.Where(a => a.RoomStatus == 1).Include(c => c.RoomType).OrderBy(a => a.Position) ;
            if (id != "")
            {
                 rooms = db.Rooms.Where(u => u.RoomTypeID == id && u.RoomStatus == 1).OrderBy( u => u.Position);
            }
            return View(rooms.ToList());

        }


        public ActionResult Index()
        {
            ViewRoomType view = new ViewRoomType()
            {
                List = db.RoomTypes.ToList(),
                Create = new QLKS.Models.RoomType()
            };


            return View(view);
        }


        [HttpPost]
        public ActionResult Index(RoomType roomtype)
        {
            if (roomtype.RoomTypeID == null)
            {
                var data = db.Database.SqlQuery<System.Int64>("exec GetNextRoomTypeSeq");
                roomtype.RoomTypeID = GlobalFunction.addDateToID(data.FirstOrDefault().ToString());
            } 
            if (ModelState.IsValid)
            {
                db.RoomTypes.Add(roomtype);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewRoomType view = new ViewRoomType()
            {
                List = db.RoomTypes.ToList(),
                Create = roomtype
            };
            return View(view); 
        }
        //
        // GET: /RoomType/Details/5

        public ActionResult Details(string id = null)
        {
            RoomType roomtype = db.RoomTypes.Find(id);
            if (roomtype == null)
            {
                return HttpNotFound();
            }
            return View(roomtype);
        }

        //
        // GET: /RoomType/Create
        [HttpGet]
        public ActionResult Create()
        { 
            return PartialView("Create", new QLKS.Models.RoomType());
        }

        //
        // POST: /RoomType/Create

        [HttpPost]
        public ActionResult Create(RoomType roomtype)
        {
            var data = db.Database.SqlQuery<System.Int64>("exec GetNextRoomTypeSeq");
            roomtype.RoomTypeID = GlobalFunction.addDateToID(data.FirstOrDefault().ToString()); 
            if (ModelState.IsValid)
            {
                db.RoomTypes.Add(roomtype);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(roomtype);
        }

        //
        // GET: /RoomType/Edit/5

        public ActionResult Edit(string id = null)
        {
            RoomType roomtype = db.RoomTypes.Find(id);
            if (roomtype == null)
            {
                return HttpNotFound();
            }
            return View(roomtype);
        }

        //
        // POST: /RoomType/Edit/5

        [HttpPost]
        public ActionResult Edit(RoomType roomtype)
        {
            if (ModelState.IsValid)
            {
                db.Entry(roomtype).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(roomtype);
        }

        //
        // GET: /RoomType/Delete/5

        public ActionResult Delete(string id = null)
        {
            RoomType roomtype = db.RoomTypes.Find(id);
            if (roomtype == null)
            {
                return HttpNotFound();
            }
            return View(roomtype);
        }

        //
        // POST: /RoomType/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id)
        {
            RoomType roomtype = db.RoomTypes.Find(id);
            db.RoomTypes.Remove(roomtype);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

code/QLKS/Views/RoomType/Create.cshtml
@model QLKS.Models.RoomType


@using (Html.BeginForm("Index", "RoomType"))
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.RoomTypeID)
    <div class="form-group">
        <div class="control-label col-md-3">
            @Html.LabelFor(model => model.RoomTypeName)
        </div>
        <div class="col-md-9">
            @Html.EditorFor(model => model.RoomTypeName)
            @Html.ValidationMessageFor(model => model.RoomTypeName)
        </div>
    </div>
    <div class="form-group">

        <div class="control-label col-md-3">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="col-md-9">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

    </div>
    <div class="form-group">
        <div class="control-label col-md-3">
            @Html.LabelFor(model => model.Depcriptions)
        </div>
        <div class="col-md-9">
            @Html.EditorFor(model => model.Depcriptions)
            @Html.ValidationMessageFor(model => model.Depcriptions)
        </div>
    </div>

    <div class="box_button">
        <button type="submit" value="Create">Thêm</button>
    </div>
}

code/QLKS/Views/RoomType/Delete.cshtml
@model QLKS.Models.RoomType

@{
    Layout = "../Shared/_LayoutPage.cshtml";
    ViewBag.Title = "Delete";
}

<div class="container">
    <div class="messagse">
        <h3>Bạn có chắc chắn xóa phòng?</h3>
    </div>
</div>
<div class="col-md-12">
    <div class="portlet light   ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Xóa Phòng</span>
            </div>

        </div>
        <div class="portlet-body">
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.RoomTypeName)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.RoomTypeName)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.Price)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.Price)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.Depcriptions)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.Depcriptions)
                </div>
            </div>
             @using (Html.BeginForm())
            {
                <div class="box_button">
                    @Html.ActionLink("Trở về", "Index")
                    <button type="submit" class="btn" value="Xóa">Xóa</button>
                </div>
            } 
        </div>
    </div>
</div>

code/QLKS/Views/RoomType/Details.cshtml
@model QLKS.Models.RoomType

@{
    Layout = "../Shared/_LayoutPage.cshtml";
    ViewBag.Title = "Xem Loại Phòng";
}
<div class="col-md-12">
    <div class="portlet light   ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Loại Phòng</span>
            </div>

        </div>
        <div class="portlet-body">
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.RoomTypeName)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.RoomTypeName)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.Price)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.Price)
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-3">
                    @Html.DisplayNameFor(model => model.Depcriptions)
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.Depcriptions)
                </div>
            </div>
            <div class="box_button">
                @Html.ActionLink("Sửa", "Edit", new { id = Model.RoomTypeID }) |
                @Html.ActionLink("Trở về", "Index")
            </div>
        </div>
    </div>
</div>

code/QLKS/Views/RoomType/Edit.cshtml
@model QLKS.Models.RoomType

@{
    Layout = "../Shared/_LayoutPage.cshtml";
    ViewBag.Title = "Edit";
}

<div class="col-md-12">
    <div class="portlet light   ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Sửa Loại Phòng</span>
            </div>

        </div>
        <div class="portlet-body">
            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true)
     

                @Html.HiddenFor(model => model.RoomTypeID)
                <div class="form-group">
                    <div class="control-label col-md-3">
                        @Html.LabelFor(model => model.RoomTypeName)
                    </div>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.RoomTypeName)
                        @Html.ValidationMessageFor(model => model.RoomTypeName)
                    </div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3">
                        @Html.LabelFor(model => model.Price)
                    </div>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Price)
                        @Html.ValidationMessageFor(model => model.Price)
                    </div>
                </div>
                <div class="form-group">
                    <div class="control-label col-md-3">
                        @Html.LabelFor(model => model.Depcriptions)
                    </div>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Depcriptions)
                        @Html.ValidationMessageFor(model => model.Depcriptions)
                    </div>
                </div>
                <div class="box_button">
                    @Html.ActionLink("Trở về", "Index")
                    <button type="submit" class="btn" value="Sửa">Lưu</button>
                </div> 
            }
        </div>
    </div>
</div>

code/QLKS/Views/RoomType/Index.cshtml
@model QLKS.Models.ViewRoomType
@{
    Layout = "../Shared/_LayoutPage.cshtml";
    ViewBag.Title = "Index";
}
<div class="col-md-12">
    <div class="portlet light   ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Loại phòng</span>
            </div>

        </div>
        <div class="portlet-body">
            @Html.Partial("Create", Model.Create)
        </div>

    </div>
</div>
<div class="col-md-12">
    <div class="portlet light   ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-pin font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Danh sách loại phòng</span>
            </div>

        </div>
        <div class="portlet-body">
            <table id="dataTables" class="table table-striped table-hover scroll">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Create.RoomTypeName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Create.Price)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Create.Depcriptions)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.List)
                    {
                        <tr>
                            <td style="width: 30%">
                                @Html.DisplayFor(modelItem => item.RoomTypeName)
                            </td>
                            <td style="width: 30%">
                                @Html.DisplayFor(modelItem => item.Price)
                            </td>
                            <td style="width: 30%">
                                @Html.DisplayFor(modelItem => item.Depcriptions)
                            </td>
                            <td style="width: 10%; min-width: 200px">
                                @Html.ActionLink("Edit", "Edit", new { id = item.RoomTypeID }) |
            @Html.ActionLink("Details", "Details", new { id = item.RoomTypeID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.RoomTypeID })
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>

    </div>
</div>

code/QLKS/Views/RoomType/Search.cshtml
@model IEnumerable<QLKS.Models.Room>
<thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Position)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().RoomType.RoomTypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().RoomType.Price)
        </th>
    </tr>
</thead>
@foreach (var item in Model)
{
    <tr>
        <td style ="width: 30%">
            @Html.DisplayFor(modelItem => item.Position)
            @Html.HiddenFor(modelItem => item.RoomNoID)
        </td>
        <td style ="width: 30%">
            @Html.DisplayFor(modelItem => item.RoomType.RoomTypeName)
        </td>
        <td style ="width: 40%;min-width: 170px;">
            @Html.DisplayFor(modelItem => item.RoomType.Price)
        </td>
    </tr>
}
<tr>
    <td colspan="3">
        <script>
            jQuery("table.roomtype tbody tr").click(function () {
                var id = jQuery(this).find("input").val();
                jQuery("#ListRooms option").each(function () {
                    if (this.value == id) {
                        jQuery(this).prop("selected", true);
                    }
                });
                jQuery(".multiple").select2();
            });
        </script>
    </td>
</tr>